### ISSUE TITLE
Motion history video needs normalization

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#101]
The motion history videos become quite dark at the moment:
![Screenshot from gJB_sFM_c09_d08_mJB0_ch08_motion_history avi](https://user-images.githubusercontent.com/114316/80459024-0ac0d080-8932-11ea-9b77-673e4941998e.png)
if you compare to the motion video of the same example: 
![Screenshot from gJB_sFM_c09_d08_mJB0_ch08_motion avi](https://user-images.githubusercontent.com/114316/80459022-098fa380-8932-11ea-9b3b-2881464b06b5.png)

I think it would be good to have some kind of weighting of the frames (or normalization). I experimented with weighting when creating some (non-motion) history videos [using FFmpeg](https://www.arj.no/2020/03/01/keyframe-displays-ffmpeg/). It could be done like a that, or perhaps even better would be to add the "tale" to the current frame. That may make the present frame stick out even more, yet still keep the motion history visible.

**Comment by balintlaczko** [comment]
Normalization is now possible via the new ffmpeg-based `history` function. To apply it, use `normalize=True`. To change the normalization strength use `norm_strength` (defaults to 1, which is full strength). When processing motion videos, it can also be useful to use smoothing via `norm_smooth`, for example with matching the `history_length`. Finally, weights can now be specified using `weights`.
