### ISSUE TITLE
Choking when working on video without audio

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#105]
I am testing some video files without audio (timelapses), and then i get into trouble: 

`FileNotFoundError: [Errno 2] No such file or directory: '../original/GH010095_motion_w_audio.avi' -> '../original/GH010095_motion.avi'`

Looks like it assumes that there is an audio stream in the file.

**Comment by balintlaczko** [comment]
Yep, good catch, I could reproduce this now. Fix is coming soon!
