### ISSUE TITLE
reimplement history() with ffmpeg

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#108]

**Comment by alexarje** [comment]
Yes, I think using the tmix function of ffmpeg could work well here. Have tested this [here](https://www.arj.no/2020/03/01/keyframe-displays-ffmpeg/).

**Comment by balintlaczko** [comment]
Yes! That post was in fact a great inspiration for my work. The `history` function is not based on ffmpeg's `tmix`, and while there are several added parameters which can be useful (such as `weights`, `normalize`, `norm_strength`, `norm_smooth`) the main improvement is still it's speed, thanks to ffmpeg it is now multicore, and *much* faster than the previous, cv2-based `history`, which was single-core.
