### ISSUE TITLE
reimplement motion() with ffmpeg

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#109]

**Comment by alexarje** [comment]
Yes, I think this could be done using the tblend function. After much fiddling around, I found a way of doing that I added to the [mgmotion object](https://github.com/fourMs/MGT-terminal/blob/master/code/mgmotion.sh) in MGT for terminal.

**Comment by balintlaczko** [comment]
Yes, while the motion video rendering part is already implemented (not pushed yet), this turns out to be slightly more complex issue, since the video frames need to be fetched as numpy arrays too, so we can create the plots and the data file(s). There is an already existing method shown [here](https://github.com/kkroening/ffmpeg-python/blob/master/examples/ffmpeg-numpy.ipynb) but since this returns the entire video as a numpy array, it takes some time (plus it does not render the actual motion video simultaneously). So now I am looking for a solution where I can pipe the motion video as a stream, do what needs to be done on the data, and then render the motion video from that (previously piped) stream. But this takes two rendering "loops", which in the end might not be faster than the current cv2-based method. Needs to be tested.

**Comment by balintlaczko** [comment]
After a *lot* of research, I (at least for now) retire this, as it seems to be impossible to get per-axis median filtering or mean on a video without losing image quality with ffmpeg. Our current (openCV-based) pipeline is the following:

input -> framediff -> threshold -> median (or erode) => motionvideo -> mean (h/v) -> stack (v/h) => motiongrams (h/v)

From these steps, the framediff, threshold, and stacking seems to be working and nice. The two problems I have is the median filter, which seems to be documented like any other filter yet somehow missing from both the Windows and Linux ffmpeg builds(?!), and the per-axis mean computation, which doesn't seem to work without a great loss of resolution. Let's say I have a 1920x1080 video. I tried:
- `scale=1:1080` -> executes, but when normalizing the result it turns out that it is very degraded in vertical resolution as well.
- the same `scale` with one of these `-flags`: `bilinear`, `bicubic` (default), `experimental`, `neighbor`, `area`, `bicublin`, `gauss`. None of these helped.
- `scale=500:1080,avgblur=sizeX=500:sizeY=1` -> still f*-d up vertical res (have to normalize result to see anything). Also, `avgblur` doesn't really tolerate extremely big sizes (the max is namely 1024, but doesn't always work, something like 500 is still quite big, but always works). `scale` also throws a lot of warnings when I want to scale either of the axes to 1.

I tested `normalize` with some videos, it does not introduce any degrading on its own, so it must be an issue with either the extreme scaling or the extreme blurring (where "extreme" refers to the aspect ratio or kernel).

There is also another issue (which I referred above), that even if I *do* manage to find a working median filter + per-axis mean, I still have to pipe the video frames into np.arrays so that we can calculate centroid, com and qom, and piping can be a bit fragile (and slow?) when processing very long videos (or not?..).

So for the time being, let's keep `motion()` openCV-based.

**Comment by alexarje** [comment]
Ah, too bad it didn't work. But thanks for trying!

**Comment by alexarje** [comment]
I have been running motion() on some long (60min+) recordings recently. They take a looong time to process. I wonder whether it would be worth having a motion method (without motiongrams) based on FFmpeg? Then that could be used if one only wants to generate a motion video and calculate QoM?

**Comment by alexarje** [comment]
I just had to cancel a motion() process that had been running for a couple of days. From just eyeballing the development of the percentage it looked like the process was non-linear, getting slower and slower towards the end. Haven't seen this for shorter videos, but it was definitely noticeable now. Need to check if there is something going on in the code that can explain that.

**Comment by balintlaczko** [comment]
Giving this yet another try now.

> From just eyeballing the development of the percentage it looked like the process was non-linear, getting slower and slower towards the end.

To me this sounds like an iteration problem, or a memory-allocation problem. Since currently we are doing the `motion()` with opencv and accumulating the motiongram cols/rows into arrays. That could grow large with some extremely long videos. How long was yours? Alternatively, there can also be a hidden issue with writing very long videos with `cv2.VideoWriter.write()`.

**Comment by alexarje** [comment]
These videos were relatively long, 10-30 minutes, full HD quality. Should do some more testing with different files.

**Comment by joachimpoutaraud** [comment]
I have been looking at how to reimplement the `motion()` function using ffmpeg. I tried to create a stream of differenciated frames using the `rawvideo` codec with the image file muxer to pipe (i.e. `image2pipe`) in order to get a faster stream than using OpenCV.

```python
command = ['ffmpeg', '-i', filename, '-filter_complex', 'format=gbrp,tblend=all_mode=difference',
           '-f', 'image2pipe', '-pix_fmt', 'rgb24','-vcodec', 'rawvideo', '-']
pipe = subprocess.Popen(command, stdout = subprocess.PIPE, bufsize=-1)
```
This results in a stream of differentiated frames in bytes which I can then transform into numpy arrays in order to apply the `musicalgestures._filter.filter_frame()` for each frame colors (i.e. RGB). I didn't find any alternatives for implementing a two dimensional median filter using ffmpeg but still, after timing the processing time of this workflow compared to the one using OpenCV, it decreases it by 40%.

I can therefore try to reimplement the `motion()` function using this ffmpeg pipeline in order to speed up the whole processing time. Moreover, I will also consider to render the different `motiondata` in a more modular way so that it is possible to only extract some of them in order to decrease the whole processing time.

**Comment by alexarje** [comment]
This would be great. The OpenCV solution is really a bottleneck, so moving to FFmpeg would be fantastic!

**Comment by joachimpoutaraud** [comment]
I just finished testing a new "raw" version of the `motion()` function using a new ffmpeg pipeline and mesured the processing time after extracting the `motiondata` on a one minute video:

- BEFORE **OpenCV** = 155.6 seconds
- NOW **FFmpeg** = 12.33 seconds !

I will now continue working on the reimplemention of the rest of the functions and test them systematically on different OS.

**Comment by alexarje** [comment]
Fantastic, what an improvement!

**Comment by joachimpoutaraud** [comment]
I have reimplemented the `motiongram()` function using ffmpeg, however it turns out that using ffmpeg filters produces some noise which create vertical lines.

Therefore, when the parameter [`equalize_motiongram`](https://github.com/fourMs/MGT-python/blob/65e8b53f8005cf7dd33102febbd604f57f4deea2/musicalgestures/_motionvideo.py#L499) is set to `True`, we can clearly see those artefacts:

![dance_mgx](https://user-images.githubusercontent.com/63192177/196421907-919496b4-753e-417a-ab09-93603dbbdccd.png)

However, if the `equalize_motiongram` parameter is set to `False`, we get the same result as if we use the [`motiongram_ffmpeg()`](https://github.com/fourMs/MGT-python/blob/65e8b53f8005cf7dd33102febbd604f57f4deea2/musicalgestures/_utils.py#L862) function:

![dance_mgx](https://user-images.githubusercontent.com/63192177/196422703-86fd3e30-a39c-4612-aee9-2cc82e85c0d5.png)

I do not know if it is possible to apply window function on the video frames but I will continue to investigate that matter.

**Comment by alexarje** [comment]
Ah, yes, that looks like effects of the keyframes. Would be interesting to see if thresholding the equalized version or amplifying the signal from the non-equalized could work?

**Comment by joachimpoutaraud** [comment]
I started readjusting the video signal with the `equalize_motiongram` parameter set to `False` by normalizing RGB and applying a temporal smoothing on 50 frames using `ffmpeg`:
`normalize=blackpt=black:whitept=white:smoothing=50`
![normalize](https://user-images.githubusercontent.com/63192177/196475521-7a7a482e-935d-472a-9054-98e8f7b38eb4.png)

I then tried to set a higher threshold value (i.e. 0.25) with the `equalize_motiogram` parameter set to `True`:
![thresh025](https://user-images.githubusercontent.com/63192177/196475821-2234f7fb-135f-4359-81a2-138580a06665.png)

Finally, after some research, I used ffmpeg and applied a temporal averaging denoiser (i.e. `atadenoise`) with the `equalize_motiongram` parameter set to `True`:
![s129](https://user-images.githubusercontent.com/63192177/196476617-86f73837-95f3-47b2-a1f0-9134439bf2cb.png)

We can still see some parts of the vertical lines but I think this is maybe the best compromise and a better solution than using OpenCV as it is 10 times faster.

**Comment by alexarje** [comment]
Great, well done! Yes, I agree. It looks fantastic and the speed increase is amazing. Looking forwards to testing this on other videos.

**Comment by joachimpoutaraud** [comment]
I just updated a new version of the repository with a new implementation of the [`mg_motion`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_motionvideo.py#L19) as well as all the related dependencies of the function (i.e. [`mg_motiondata`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_motionvideo.py#L429), [`mg_motionplots`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_motionvideo.py#L508), etc.). All motion processing runs now using `ffmpeg`. I will be curious to know if you are facing any problems while running it!  

I have also added the possibility to render only specific motion analysis using the new paramater `motion_analysis`. Here is an example for rendering a motion analysis based on area of motion only.
 
```python
source_video = musicalgestures.MgVideo('/path/to/source/video.avi') # load the video
# motion = source_video.motion() # renders all motion analyses
motion_aom = source_video.motion(motion_analysis='aom') # renders only area of motion. 
# You can also specify 'com', 'qom' and soon 'velocity'!
```
