### ISSUE TITLE
Videograms of extremely long videos

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#127]
There is a limitation how big images FFMPEG can make, explained in [this](https://video.stackexchange.com/questions/28408/how-to-fix-ffmpeg-picture-size-32768x16384-is-invalid) thread. I ran into the problem while trying to make a videogram of the 8-hour [Bergensbanen](https://nrkbeta.no/2009/12/18/bergensbanen-eng/) video. I think it would be wise to implement batch processing so that such videos can still be analysed. I am thinking about something like this:

processing extremely big videos in batches:
- extract a batch where num_pixels <= int_max
- make videogram
- delete extracted video
- extract next batch where num_pixels <= int_max
- etc
...
- stack all output images (possibly with another tool such as imagemagick?)

Alternatively in such cases we can issue an automatic `skip()` on the input file, until we reach a framecount which can still be processed by ffmpeg. The Bergensbanen video is roughly 3x longer (in terms of framecount) than the possible maximum, so giving it a `skip=2` should solve the issue. But in this case there is another problem, which is that we have to convert a very large .mov file into .avi, which sound like asking for trouble. The user can of course use the `skip_frames_ffmpeg()` function from `_utils.py` "manually", and then try the `mg_videograms()` from `_videograms.py`, but that is not that smooth, and all this manual work  could be spared if in `_videoreader.py` the conversion could be disabled optionally. This would mean that - in their current forms - contrast/brightness and cropping operations would not be possible, but the process of making videograms on extremely long videos would in turn be simpler.

**Comment by balintlaczko** [comment]
The issue is a bit simpler now that `skip_frames_ffmpeg()` is the default (just like in the case of contrast/brightness adjustments with `contrast_brightness_ffmpeg()` so no conversion is needed).

**Comment by balintlaczko** [comment]
The function now automatically calls a skipping process with the minimum skipping necessary to avoid integer overflow. Should work, but testing this on my humble laptop would take days of rendering, so let's reopen this in case we find out it doesn't work.

**Comment by alexarje** [comment]
Cool. Yes, this is an important thing to have working. We often have many-hour-long videos that we want to process, so an automagic skipping function sounds like a good idea.
