### ISSUE TITLE
Structure audio-related processes into class

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#140]
I think it would be beneficial to collect all audio processes under and `audio` class. Similarly how you can now call `MgObject.flow.sparse()` and `MgObject.flow.dense()` I think it would be nice to interface the audio functions like these:
`MgObject.audio.spectrogram()` (currently `MgObject.spectrogram()`)
`MgObject.audio.descriptors()`

This way if we later add more audio functions it can be done in a more organized manner.

**Comment by alexarje** [comment]
Yes, I agree!

**Comment by balintlaczko** [comment]
This is accomplished now in `MgObject.audio.spectrogram()`, `MgObject.audio.descriptors()` and `MgObject.audio.tempogram()`. Additionally, there are also the "standalone" functions of these as `mg_audio_spectrogram()`, `mg_audio_descriptors()`, and `mg_audio_tempogram()`. These can also be examples for adding other functions in the future.
