### ISSUE TITLE
new ffmpeg build changed how normalize behaves

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#145]
FFmpeg changed the source for its Windows builds. I reinstalled my OS, so downloaded the new version. Pros: this one includes the median filter! Cons: the normalize filter somehow behaves differently now, and videograms started to look quite washed out:
![dance_vgy](https://user-images.githubusercontent.com/45127463/96601581-73da3d00-12f2-11eb-847d-c41c334015c1.png)
It could be that they changed something with pixel formats, so I will try out some conversions with the format filter.

**Comment by balintlaczko** [comment]
Different pixel formats didn't help, but I noticed that the `normalize` filter got partly broken(?) in the new version, since no matter what is the `strength` value (tried: 1, 0.5, 0.25, 0.1), `independence=1` and `independence=0` produce the exact same result.

**Comment by balintlaczko** [comment]
The more I investigate this the more I see that the issue is something that has changed in the way the `normalize` filter works... According to the documentation:
"Normalize RGB video (aka histogram stretching, contrast stretching)"
If I go to GIMP and choose *Colors > Auto > Stretch Contrast*, then unchecking *Keep colors* (so that it is independently stretching each channel), and check *Non-linear components* I get the exact same results as I used to with ffmpeg's `normalize=independence=1`.
[...some time later...]
Dived into earlier versions, and can confirm that on ffmpeg 4.2.2 (using the one which ships with imageio, the current version would be 4.3.1) I get the results I am used to. (I could also check that this earlier build does *not* include the median filter, which also corresponds to my earlier experience.) 
Now the question is: how to update my code so that it respects the *new* behavior of `normalize`?

**Comment by balintlaczko** [comment]
Today I reconfirmed the problem with the official 4.2.2 static build I fetched from the internet archive. On 4.2.2 `normalize` works as expected, on 4.3.1, it produces a completely different result.
| ffmpeg v4.2.2  | ffmpeg v4.3.1  |
|---|---|
| ![dance_vgy_old](https://user-images.githubusercontent.com/45127463/96715810-68474e80-13a4-11eb-8d7a-e8e715b63f0e.png) | ![dance_vgy](https://user-images.githubusercontent.com/45127463/96716013-c1af7d80-13a4-11eb-8dc9-ff5acdf13d3e.png) |

**Comment by balintlaczko** [comment]
Tried fiddling around with different pixel format conversions, selectively compressing/stretching the luma channel, but there seems to be an obvious problem with `normalize`. I think they changed the way it detects value ranges (some of the [commits](https://github.com/FFmpeg/FFmpeg/commits/master/libavfilter/vf_normalize.c) point in that direction), but the parts of libavfilter which handles different pixel formats has also changed, so it is hard to guess where the problem lies exactly.
But this is wasting a lot of precious dev time for us now, so I came up with the following (hopefully temporary) solution:
- we will use the ffmpeg executable which comes with `imageio_ffmpeg`. This is v4.2.2 in which `normalize` works pretty well.
- alternatively I can also try copying their approach and include executables for each platform (v4.2.2) in our repo, maybe this would be more future-proof. In this case I should also include binaries for ffplay and ffprobe, so there is no separate ffmpeg installation required from the user (+1 for convenience...)
- I will rewrite the ffmpeg backed in musicalgestures, so in case of any platform, it always uses the included binaries. This way I can make sure that the ffmpeg I test with will be the ffmpeg the user interacts with as well...

Curiously I couldn't find anyone complaining about this on the internet, so if anyone reading this finds something I am open for suggestions.

**Comment by balintlaczko** [comment]
All hail the ffmpeg team! In less than an hour from [reporting the bug](https://trac.ffmpeg.org/ticket/8954#comment:2) they fixed it, and I can confirm that `normalize` is back to normal on [the latest git build](https://github.com/GyanD/codexffmpeg/releases/tag/2020-10-28-git-e5be4c5a88). YAAY!

**Comment by alexarje** [comment]
Great, well done. Bug reporting helps!
