### ISSUE TITLE
Auto-download openpose models upon their first attempted use

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#157]

**Comment by alexarje** [comment]
Since it is so big, it may be worth asking if people want to install the models or not.

**Comment by balintlaczko** [comment]
The strategy will be:

If you run `pose()` but you don't have the model you specified:
ask to download (just that one model) -> if yes, check the OS (unix or windows) -> download model -> contiue with `pose()`

**Comment by balintlaczko** [comment]
Done. Tested on Windows, works well. Will make an issue to test it on Linux as well.
