### ISSUE TITLE
Test automatic pose model file download on linux

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#160]

**Comment by balintlaczko** [comment]
On unix executing the shell scripts seems to need elevated privileges.

**Comment by balintlaczko** [comment]
(Oops seems like Github Desktop randomly closed the issue on my Ubuntu VM.)
Anyway, implemented handling sudo password. Now the models will download properly on Linux (tested on Ubuntu).

**Comment by alexarje** [comment]
Can confirm that it works correctly on Ubuntu 20.04. The only thing I was puzzled about was which password it asked for? A user may think it is a password to the login site. So perhaps ask for "sudo password" or "system password" and explain that this is for installing new files on the system?

**Comment by balintlaczko** [comment]
Yes, that's true it's a bit unclear what that password refers to. I guess I will just replace it with the standard `[sudo] password for $USER:` prompt.
