### ISSUE TITLE
old cv2-based motion() sometimes freezes

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#162]
Happens very rarely, but it happens... It does not seem to be related to CPU level, and I previously ruled out the progress bar as a possible culprit. (Maybe a jupyter notebook issue?) The process continues to consume the same amount of CPU, but hangs forever until I brutally restart the kernel.

**Comment by balintlaczko** [comment]
Changing the `MgProgressbar` to be less responsive (now it updates only every 250 ms instead of the previous 100) seems to eliminate the freezing, at least in my test environment.

On the other hand, memory consumption is a growing concern of mine, and I suspect that the kernel deaths in the notebook can happen due to reaching memory limit (and maybe dying before being able to throw a `MemoryError`?..). Seemed like having more frequently updating progress bars worsened the problem, but they didn't cause the problem alone. It happened several occasions that the kernel died just _after_ the frame-loop was over (and thus the progress bar was no longer doing anything) and progress was 100%, and when it actually had to return all the accumulated numpy arrays (for motiongrams and data csv).

And it is easy to see actually that the larger the input video will be, the bigger the threat of "choking" will get. If the problem persists with large files, we can think about trying to redesign the process with writing temporary data files instead of accumulating large arrays in memory.

**Comment by alexarje** [comment]
I haven't noticed any problems with my testing (but I also have a lot of memory on my computer). May be more of an issue if running on servers/VDIs with limited resources, I guess. Updating every 250ms is fine. I guess it could be even slower (500ms?) if that is an issue. 

Writing to disk instead of memory may help, but could perhaps add a lot of code?

**Comment by balintlaczko** [comment]
No, I was actually thinking about some way to manage temp files with `numpy.ndarray.save`. But probably accumulating the motiongrams in memory are not such a big issue as I thought, if we calculate an 8-bit color 1920*1080px 60FPS video, even with 8 hours length, the two motiongram arrays should be around 4.82 GB size together (in memory). Which is not unreasonable, considering the task. But there might be other things consuming memory, which I am still investigating...

Yes, I will change the default update rate to 500ms, I also think that is totally sufficient.

**Comment by balintlaczko** [comment]
Haven't seen this problem for ages. will reopen if it comes up again.
