### ISSUE TITLE
Choking when no audio stream in video file

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#172]
I am testing various things now and see that video files without an audio stream create problems when trying to create a .wav file in one of the scripts. Then FFmpeg returns: 

    Output file #0 does not contain any stream

So there should be a check to see if the input file does, indeed, contain an audio stream before attempting to write an audio output.

**Comment by balintlaczko** [comment]
Good catch, thanks! Can you tell which function returns this? I use the `_utils.has_audio` function in the `_videoreader`, and pass the info to processes like `pose`, `flow` or `motion`, so that they only try to extract the wav file if there is one. It seems to work with my test-silent-video, but I might have missed this in one of the functions.

**Comment by alexarje** [comment]
Here is  a little more output from my testing: 

> Input #0, avi, from '/home/alexander/github/MGT-python/testing/15hours_motion.avi':
> [...]
> /home/alexander/github/MGT-python/testing/15hours.wav: No such file or directory
> Traceback (most recent call last):
>  File "mgt.py", line 12, in <module>
>    musicalgestures.MgObject(video).motion().average()
>  File "/home/alexander/anaconda3/envs/magenta/lib/python3.7/site-packages/musicalgestures/_motionvideo.py", line 270, in mg_motionvideo
>    embed_audio_in_video(source_audio, destination_video)
>  File "/home/alexander/anaconda3/envs/magenta/lib/python3.7/site-packages/musicalgestures/_utils.py", line 443, in embed_audio_in_video
>    os.rename(of + '_w_audio' + fex, destination_video)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/alexander/github/MGT-python/testing/15hours_motion_w_audio.avi' -> '/home/alexander/github/MGT-python/testing/15hours_motion.avi

**Comment by balintlaczko** [comment]
Thanks! I have very different line numbers here, the `embed_audio_in_video(source_audio, destination_video)` in *_motionvideo.py* is at line 414, and the `embed_audio_in_video` function in *_utils.py* is at line 932. Could it be that you are using an earlier version of the package/repo?

Please try with your silent video:
```
from musicalgestures._utils import has_audio
video = '/path/to/silent_video'
print(has_audio(video))
```
It should print `False`. Is that successful?

**Comment by alexarje** [comment]
Yes, indeed, I see now that I used the pip install version on this laptop. Uninstalled it through pip to be sure that I use the current version. Then the audioless video files worked well. Sorry about the noise.
