### ISSUE TITLE
Similarity matrix

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#173]
To look for periodicities, it would be interesting to implement a function to create a similarity matrix from a motiongram (and spectrogram). The idea would be to shift the matrix 90 degrees and multiply with the unshifted version to get a new matrix that shows similarities and differences over time. The matrix would have to be reduced to a square first.

**Comment by joachimpoutaraud** [comment]
I have started looking at implementing Self-Similarity Matrix (SSM) for motiongrams as well as spectrograms and got some interesting results while basing my work on an [notebook](https://www.audiolabs-erlangen.de/resources/MIR/FMP/C4/C4S2_SSM.html) made by Meinard Müller.

Here is an overview of a motiongram SSM:
![ssm](https://user-images.githubusercontent.com/63192177/185356037-eb96c567-0985-4acf-8fda-cf8746327101.png)

I will now work on implementing the function in the toolbox.

**Comment by alexarje** [comment]
Very nice. Yes, it would be interesting to use this for looking at recurrent patterns!

**Comment by joachimpoutaraud** [comment]
I just pushed the new `ssm` function in the MGT. This allows to look for periodicities on `motiongrams`, `spectrogram`, `chromagram` and `tempogram`. More information can be found [here](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#ssm).

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI shortly.
