### ISSUE TITLE
New lines in progressbar update

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#186]
When I run a python script in the terminal (on Ubuntu 20.04), the progress bar creates a new line for each percentage of update: 

![Screenshot from 2021-01-14 17-30-37](https://user-images.githubusercontent.com/114316/104625877-85cf4000-5695-11eb-9b43-0fdc2840c354.png)

Possible bug?

**Comment by balintlaczko** [comment]
Good catch, Alexander, this seems to be an issue on  Linux (tested on Ubuntu in VM). On Windows it seems to work as expected. I suspect that the `sys.stdout.flush()` works differently on unix(?). Will look into it now.

**Comment by balintlaczko** [comment]
Update: this is a very specific problem which happens ONLY when your Terminal window is not wide enough to print the progress bar on a single line. I can actually confirm the same behavior on both Windows and Ubuntu: if the window is not wide enough, it happens, if it is wide enough, it doesn't happen.

**Comment by balintlaczko** [comment]
`shutil` to the rescue!

![image](https://user-images.githubusercontent.com/45127463/104636679-0432de80-56a4-11eb-817f-3dc3ce9d2384.png)

![image](https://user-images.githubusercontent.com/45127463/104636814-393f3100-56a4-11eb-82bf-33ceb03b979f.png)
