### ISSUE TITLE
Manual cropping window crashes when having space or parentheses in filename

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#187]
I had problems getting the cropping function to work: 

![Screenshot from 2021-01-15 10-37-49](https://user-images.githubusercontent.com/114316/104708316-d68a7b80-571d-11eb-85a4-7b7c31af2c63.png)

but realized that it was because I had parentheses in the video file name. Would it be possible to have a file name check somewhere? Or write something about file naming in the wiki?

**Comment by balintlaczko** [comment]
Yes, could reproduce it on both OS-es. On Windows only spaces in the file name causes this, on Ubuntu either spaces and parentheses in the file name will trigger it.

**Comment by balintlaczko** [comment]
This was two separate problems, the spaces were because of #192, the parentheses seems to be a bash thing. For
`ffmpeg -y -i dance(1).avi -frames 1 dance(1).png` I got:
<pre>bash: syntax error near unexpected token `(&apos;
</pre>

**Comment by balintlaczko** [comment]
Just finished tracking down another incredibly hard-to-find bug: `moviepy.editor.VideoFileClip` will hang forever (without errors or any response) if the file name has either a space _and_ parentheses (like "video (1).avi"), OR just an opening parenthesis (like "video(1.avi"). This might be a bug in `ffmpeg_parse_infos()` on line 225 in _moviepy/video/io/ffmpeg_reader.py_.

**Comment by balintlaczko** [comment]
With the `moviepy` dependency removed + the `wrap_str` and `unwrap_str` implemented in __utils.py_, this is working fine now. Tested on Ubuntu & Windows, notebook & terminal.
