### ISSUE TITLE
Crop/trim confusion

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#188]
I see that when I do both trimming and cropping to a file, it will save the *trimmed* file with "_crop" (should be "_trim"). However, the final trimmed+cropped file is labelled correctly as "_trim_crop".

**Comment by alexarje** [comment]
Ah, now I see what happens. It actually creates the "_trim" file, but it is deleted once the cropping is done. It may be that we should just leave the trimmed file instead of deleting in. Sometimes I realize that the cropping was wrong, and then it can be nice to work directly with the trimmed file?

**Comment by alexarje** [comment]
But then again ther is the "keep_all=True" possibility. Ok, so everything is fine. User error!

**Comment by balintlaczko** [comment]
Yes, in the preprocessing stage we make one video per process in this order: trim -> skip -> rotate -> contrast/brightness -> crop -> grayscale. For each new process we use the resulting video file from the previous step. By default we keep only the end result, but yes, with `keep_all=True` all steps will be preserved.
