### ISSUE TITLE
Add waveform

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#189]
I have already suggested the edition of coloured waveforms (#159). But an easier first thing would be to add just a normal waveform audio.waveform().

**Comment by balintlaczko** [comment]
So far so good. Still needs: 
- testing on Windows in Notebook, and on Linux (terminal & notebook).
- docsstrings
- demo in notebook

![dance_waveform](https://user-images.githubusercontent.com/45127463/110007335-d882bb00-7d1a-11eb-932f-d7cd3f3d92b6.png)

![dance_spectrogram_waveform_descriptors](https://user-images.githubusercontent.com/45127463/110007371-dfa9c900-7d1a-11eb-9e89-e609f1240b44.png)

**Comment by balintlaczko** [comment]
Tested on Linux as well, all good!
