### ISSUE TITLE
Fixed-frames addition to skip frames function

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#197]
When batch processing long video files, and files of different duration, it would be good to have the ability to specify a fixed target number of frames to extract. For example, if one specifies "frames=2000", the script would find the skip-frame number that would result in the total number of output frames to be less than 2000 files.

**Comment by joachimpoutaraud** [comment]
I just added a new `frames` parameter to the `MgVideo` object which is useful to specify a fixed target number of frames to extract. As a result, if one specifies `frames=2000`, the script will find the skip-frame number that would result in the total number of output frames equal to that specified in the parameter.  More information can be found [here](https://github.com/fourMs/MGT-python/wiki/3-%E2%80%90-Preprocessing#fixing).

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI with some other functions shortly.
