### ISSUE TITLE
Segmentation fault on cv2.waitkey on Linux

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#200]
In cropvideo, at line 358:
```
        while(1):
            cv2.imshow(name_str, frame_scaled*(frame_mask != g_val) +
                       frame_mask.astype(np.uint8))
            k = cv2.waitKey(1) & 0xFF
            if k == ord('c') or k == ord('C'):
                break
``` 
This will throw a segmentation fault error on Linux.

This:
```
        while(1):
            cv2.imshow(name_str, frame_scaled*(frame_mask != g_val) +
                       frame_mask.astype(np.uint8))
            k = cv2.waitKey(1) & 0xFF
            if k == 27:
                break
``` 
...will work but only if I press the correct key (escape), any other key will cause segmentation fault.

**Comment by balintlaczko** [comment]
[This person](https://www.reddit.com/r/opencv/comments/ix55pu/bug_opencvpython_segfault_when_losing_window/) had a similar issue, though losing window focus is OK in our case.

**Comment by balintlaczko** [comment]
It seems to be that everything works fine when the code is executed inside the notebook, the segfault only comes when working from the terminal.

**Comment by balintlaczko** [comment]
It became surprisingly challenging to tackle this. The main problem seems to be now that if we do not include a `cv2.waitKey` in the loop, then the image won't show at all (only a small, black and unresponsive window). But if we have `cv2.waitKey` - even when we don't even query it - then whatever key I will press will instacrash python (with the segfault).

Not sure if there is any way to fix this other than reimplementing the entire thing in something else (like tkinter).

**Comment by balintlaczko** [comment]
Tkinter actually has an array of commonly known problems with displaying image files. Too deep of a rabbit hole.

I am onto something now based on the clue that the problem only occurs _outside_ the notebook. Now I am trying to "emulate" a notebook-like event loop via `asyncio`, and I seem to get the basic functionality of showing an image in a named window and exiting on a specific key (with not exiting on other keys, and without segmentation faults in any case).
Unfortunately to fully test this with the interactive rectangle drawing the code needs quite a bit of refactoring - but it might actually avoid the bug. (yay!)

**Comment by balintlaczko** [comment]
OK, found it, or at least a step closer. I managed to create an incredibly hacky - but _working_ - fix involving creating another python file, which I run in an asynchronous subprocess calling another instance of python, and saving the printed stdouts into global variables. (Phew...) But it only works if NOTHING from the package is imported. Any (even the most unrelated and unused) imports and it _will_ crash with segmentation fault. Doesn't matter if the function will actually be used or not. And it does not crash immediately, but on the `cv2.waitKey()` - and only when not called from a jupyter notebook.

**Comment by alexarje** [comment]
Ah, this seems tricky... I guess you should just try to find a pragmatic solution here...

**Comment by balintlaczko** [comment]
It _is_ tricky indeed, well in my top-3 toughest bughunts :) but now I can finally see the light in the end of the tunnel (also learned "accidentally" a lot about multithreading/multiprocessing/concurrency while trying to crack the problem, which will be perfect to make the cv2-based processes multicore!).
Now I have a hacky but working solution, but that involves a lot of code-copying (- as I described above, any imports will cause the segfault on `cv2.waitKey` - it is still a mystery why exactly there and why not immediately upon import...), now I am trying to restructure the code so that only that cropping window-UI part is migrated to the async subprocess (so there is no _need_ for any imports or copied functions, really).

**Comment by balintlaczko** [comment]
This is fixed now. Tested on Linux (shell vs notebook) and Windows (also shell vs notebook).

**Comment by okawo80085** [comment]
yeah so.... this is still a problem, i have a fresh ubuntu 20.04 lts machine that segfaults on any button except `esc` and `space`, tested on a few last versions of opencv-python

about to try the your crazy workaround, but i also have a question: 

why is `waitKey` is the only way to update the windows in python? its not a problem for me to get keyboard input from a different source, but i cant update the windows without waitKey which *literally* kills my program when i press almost any key

any thoughts?

**Comment by okawo80085** [comment]
after some testing on that machine, and trying your workaround, i found out 2 things

first is that, at least on that machine, its caused by a matplotlib import

and the second thing i found is that no matter what i do if matplotlib is imported at any point before the waitKey call it segfaults, so i had to move my plotting logic into a file that a run with an async subprocess call, write the plot into a file, then read it in my original process, basically your workaround except i use files

now, this feels like a really low level issue, not sure where exactly, didnt look at the source code and pretty sure i wont even try to fix this, its only an issue on that machine

**Comment by Hirosam1** [comment]
Yes this bug, also is happening to me. Maybe we should open a new issue?

**Comment by okawo80085** [comment]
yeah a new issue both for `matplotlib` and `opencv`, its not clear why exactly the `matplotlib` import causes the seg fault, it can be either of the two or both

**Comment by creikey** [comment]
I'm experiencing this as well, the wonders of modern software
