### ISSUE TITLE
PySoundFile failed

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#207]
When testing the new wavefunction on Ubuntu I get a "PySoundFile failed" error: 

![Screenshot from 2021-03-05 08-48-58](https://user-images.githubusercontent.com/114316/110084041-c42cd580-7d8f-11eb-8675-9c79d5db4e33.png)

The function still works, though.

**Comment by balintlaczko** [comment]
This warning is now suppressed.
