### ISSUE TITLE
Analysis examples

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#211]
It would be good to have some more visualization examples, such as plotting QoM values with [violin plots](https://towardsdatascience.com/violin-plots-explained-fb1d115e023d) or [raincloud plots](https://github.com/RainCloudPlots/RainCloudPlots/blob/master/tutorial_python/raincloud_tutorial_python.ipynb).

**Comment by joachimpoutaraud** [comment]
I just updated the `motionplots()` function and added a violin plot visualization for the QoM. This renders the medians of the quantity of normalized pixels. More information can be found [here](https://github.com/fourMs/MGT-python/issues/211).

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI with some other functions shortly.
