### ISSUE TITLE
Test on MacOS

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/MGT-python#224]

**Comment by balintlaczko** [comment]
Let users know:
- to install ffmpeg via `brew install ffmpeg`
- to install wget via `brew install wget`

**Comment by balintlaczko** [comment]
Model download seems to have the same issue as it used to be in Colab.

**Comment by balintlaczko** [comment]
Everything seems to work fine after the first test run. There is only a small problem with the model download shell script, which I have to figure out. So far so good.

**Comment by alexarje** [comment]
There were no complaints by Mac people during the last workshop. So I close this one for now.
