### ISSUE TITLE
Face blurring

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#247]
There is an increasing need to have a quick and easy way to blur people's faces in cases where we want to anonymize video recordings before sharing. Would be useful to have a function for this.

**Comment by alexarje** [comment]
I have played with [deface](https://github.com/ORB-HD/deface) now, a tool for video anonymization by face detection. First, it didn't work, but when I upgraded imagio, it works like a charm. Think it would be great to implement this in MGT.

**Comment by alexarje** [comment]
I have tested [deface](https://github.com/ORB-HD/deface) on several different videos now and it works really well. Since it tracks all the faces in the video so well, it would also be relevant to store information about the coordinates of the faces in a text file for further analysis.

**Comment by joachimpoutaraud** [comment]
The function `blurfaces` has been added to the MGT with the possibility to store the coordinates of the faces in a text, csv or tsv file for further analysis. More information can be found [here](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#blur)
