### ISSUE TITLE
Rename MgObject

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#248]
I wonder whether we should rename MgObject() to readfile(). That would be easier for beginners. Not sure how much that would break things or if it is better to set up an alias function?

**Comment by balintlaczko** [comment]
I agree that the name "mgobject" is not so descriptive, so it could be problematic for beginners. At the moment, an `MgObject` holds a video file, and we then do stuff with that video via calling different methods of `MgObject`. When I made the classes for images, figures, and lists, I named them `MgImage`, `MgFigure` and `MgList`. The reading of the video file is not imperative (`MgObject.readfile()`) but declarative (`MgObject('/path/to/file')`), so what if we just rename it to what it is: `MgVideo`? Then it would also follow the same logic as the other class names.

**Comment by alexarje** [comment]
Yes, I think MgVideo makes sense. At a later stage we may also want to add mocap files, but then we could do something like MgMocap.

**Comment by balintlaczko** [comment]
Updated notebook and Wiki pages.

**Comment by balintlaczko** [comment]
`MgObject` is hereby renamed to `MgVideo`! :)
