### ISSUE TITLE
Add grid function

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#250]
It is sometimes useful to create grid-based visualizations of a video file. I have found a [code snippet](https://github.com/fourMs/MGT-terminal/blob/master/code/mggrid.sh) that does this easily with any number of images, such as 3x3:

![flamenco_grid_3x3](https://user-images.githubusercontent.com/114316/146513702-c0402575-041f-4965-ae7f-cc6582743759.jpg)

or 7x7: 
 
![flamenco_grid_7x7](https://user-images.githubusercontent.com/114316/146513645-283439e5-e8c4-46c6-868c-4d140b5f69d4.jpg)

Would be cool to add this to the toolbox as well.

**Comment by joachimpoutaraud** [comment]
Just added a new grid-based video preview to the toolbox, some documentation can be found here : [grid-based video](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#grid)
