### ISSUE TITLE
Crop problem

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#258]
I am struggling to make the cropping to work. When doing it in ipython on Ubuntu, I get the error "w is not defined":

![Screenshot from 2022-06-29 23-50-26](https://user-images.githubusercontent.com/114316/176756829-3f084ea2-45f6-4629-bde9-8b0dfa325fc7.png)

**Comment by joachimpoutaraud** [comment]
I just tried to run it using Windows Subsystem for Linux (WSL) and it worked fine. Which version of the MGT-python are using?

**Comment by alexarje** [comment]
It was with 1.2.1. I cannot reproduce with 1.2.2. Now I struggle to make it work in ipython, but think it may be a problem with Wayland. It works in Jupyter, although there I have a scaling problem which may be screen resolution dependent. I only see a small part of the (4K) video. These may be Ubuntu-specific problems, though, so will investigate a little more with various settings.

![Screenshot from 2022-07-05 23-49-50](https://user-images.githubusercontent.com/114316/177540143-b2b65894-756a-4f67-9d49-9b31bd29c4fc.png)
