### ISSUE TITLE
AoM in combined plot

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#259]
With the calculation of the area of motion, it would be useful to plot it together with CoM and QoM in motion(). Perhaps make a combined plot with CoM and AoM in the first row, and then a double-column with QoM in the second row?

**Comment by alexarje** [comment]
I see that the AoM is mentioned in the combined plot in the documentation, but it may not be added to a release yet? In any case, I think it would be nice to have the QoM on a separate row so that it is easier to follow the timeline.

**Comment by joachimpoutaraud** [comment]
I have update the `motionplots` with the QoM on a separate row. Here is an [overview](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#motionplots) of the new visualization.

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI with some other functions shortly.

**Comment by alexarje** [comment]
Great!
