### ISSUE TITLE
Automagic grid counting

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#260]
Great to have the grid() function in place. Could you also add a function so that it automatically detects the skip frame number based on the number of frames in the video? So that if it makes a 3x3 grid, they will be equally sampled from the whole video? 

There is example code [here](https://github.com/fourMs/MGT-terminal/blob/master/code/mggrid.sh), with both a FFprobe and FFmpeg option for counting the number of frames.

**Comment by joachimpoutaraud** [comment]
I have added the automatic detection of the `nth_frames` based on the number of frames in the video using opencv. Here, is the new version of the [code](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_grid.py/#L33). 

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI with some other functions shortly.
