### ISSUE TITLE
Heatmap of face detection

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#262]
Now that we have the blur_faces() in place with data export, it would be really cool to also create some visualizations based on the data. What about some heatmaps [like the ones here](https://github.com/pedro-lucas-bravo/master_thesis_data_analysis/blob/main/7-users.ipynb)?

**Comment by joachimpoutaraud** [comment]
I just pushed an new version of the `blur_faces()` function and added the `draw_heatmap` parameter which allows the user to draw heatmap of face detection. More information can be found [here](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#heatmap).

This is only available on the local repository at the moment but I will update a new version of the repository on PyPI with some other functions shortly.
