### ISSUE TITLE
Store coordinates per frame in blur_faces()

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#263]
It looks like blur_faces() now stores XY pairs on new lines. Then it is difficult to know which ones belong together within a frame. I guess the number of detected faces might vary for each frame, so it doesn't make sense to write many columns per frame. But perhaps you could write the timestamp or frame number in the first column?

**Comment by joachimpoutaraud** [comment]
I have added the [timestamp (in milliseconds)](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_blurfaces.py#L155) to the data storage of the `blur_faces()` function. Each detection of the faces is now noted with its corresponding timestamp in milliseconds. The updated function is only available in the local repository at the moment but I will update a new version of the package asap.
