### ISSUE TITLE
New info() function

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#264]
I think it would be useful to have an info() function or another way of getting information about the basic features of the loaded video file. Pixel dimensions, duration, and the number of frames come to mind, but possibly some others (colorspace). Parts of this information are captured by other functions already, but could perhaps be structured in such a way that they are readily available?

**Comment by joachimpoutaraud** [comment]
I have added a new `info()` function to retrieve technical metadata from video, audio and format. The function has been added to the `__init__.py` file as it might be useful in several cases. Moreover, I have updated the [3- Preprocessing](https://github.com/fourMs/MGT-python/wiki/3-%E2%80%90-Preprocessing) wiki page and added the [info](https://github.com/fourMs/MGT-python/wiki/3-%E2%80%90-Preprocessing#info) documentation there.
