### ISSUE TITLE
Offset error in impacts() 

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#265]
When I try to run the impacts() function with the settings from the tutorial: 

`impact_detection = v.impacts(detection=True, local_mean=0.1, local_maxima=0.15)`

I get an error that sounds like a pixel offset error problem. See attached screenshot: 

![Screenshot from 2022-07-04 12-47-24](https://user-images.githubusercontent.com/114316/177539617-59b70820-1704-4ecf-ab89-915078be5c6b.png)

**Comment by joachimpoutaraud** [comment]
@alexarje can you tell me the FPS of the file you used? This might maybe related to this. On the other hand, is it possible to plot more information of the issue, like where does it happens inside the `impacts` function?
