### ISSUE TITLE
Issues with info() in ipython

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#267]
Trying the new info() function on Ubuntu, but getting the same error message in both ipython and in Jupyter. Looks like a utf formatting issue? 

![Screenshot from 2022-07-10 23-11-03](https://user-images.githubusercontent.com/114316/178162247-f4fdb994-f960-4e4d-9d91-55ca7c2c44b7.png)

**Comment by joachimpoutaraud** [comment]
Yes might have been related to the utf-8 encoding, I have updated the function which should work fine now! However, it is only available in the local repository at the moment.
