### ISSUE TITLE
Pose extraction  - Issue and Fix -  Can't open pose_iter_440000.caffemodel" in function 'cv::dnn::ReadProtoFromBinaryFile

### ISSUE THREAD

**Issue by balandinodidonato** [fourMs/MGT-python#269]
**Experienced and tested on Windows 10 Pro with Python 3.10.7**

I tried to run the Pose extraction feature, and I came across an issue. To summarise, Python could not open pose_iter_440000.caffemodel" in function 'cv::dnn::ReadProtoFromBinaryFile

Here is the **Python script** I've used to extract the pose:

`import musicalgestures`
`source_video = musicalgestures.MgVideo('pianist.avi')`
`pose = source_video.pose(downsampling_factor=1, threshold=0.05, model='coco', device='gpu', save_data=True)`
`source_video.show(key='pose')`

Here is the **terminal output** and the error I got.

`PS C:\> python test.py`
`Could not find weights file. Do you want to download it (~200MB)? (y/n)`
`y`
`Traceback (most recent call last):`
`  File "C:\test.py", line 3, in <module> `
`    pose = source_video.pose(downsampling_factor=1, threshold=0.05, model='coco', device='gpu', save_data=True)`
`  File "C:\Users\Balandino Di Donato\pyver\lib\site-packages\musicalgestures\_pose.py", line 89, in pose`
`    net = cv2.dnn.readNetFromCaffe(protoFile, weightsFile)`
`cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1138: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "C:\Users\Balandino Di Donato\pyver\lib\site-packages\musicalgestures/pose/coco/pose_iter_440000.caffemodel" in function 'cv::dnn::ReadProtoFromBinaryFile'`

**How to Fix**

With some research I came across [this issue](https://github.com/spmallick/learnopencv/issues/409) and they suggest:
>DNN weighs are large and not stored in get repository. Please download them before the code execution. In case if you use Linux or Mac you can run getModels.sh script to do it automatically. Please download files manually with link in Readme.md, if you run code on Windows.

I've downloaded  the [OpenPose repository](https://github.com/CMU-Perceptual-Computing-Lab/openpose) and copy pasted the [pose models](https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models/pose) "'C:\Users\Balandino Di Donato\pyver\lib\site-packages\musicalgestures\'. This seems to have fixed the issue.

Maybe there is a more elegant solution out there?

**Comment by alexarje** [comment]
Great, thanks for the workaround. Not sure if you have any other suggestion @balintlaczko @joachimpoutaraud ?

**Comment by joachimpoutaraud** [comment]
Hi @balandinodidonato and thank you for reporting this issue.  It seems that the pose [function](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_pose.py#L344) didn't download the model on your computer as it should normally.

Could you please try to run the following function and see if the `caffemodel` is properly downloaded in your current path?

```python
def download_model('coco'):
    """
    Helper function to automatically download model (.caffemodel) files.
    """
    import platform
    import subprocess
    import os
    import musicalgestures

    module_path = os.path.abspath(os.path.dirname(musicalgestures.__file__))
    batch, shell, shell_colab = '_remote.bat', '_remote.sh', '_remote_colab.sh'

    the_system = platform.system()

    pb_prefix = ''
    coco_script = module_path + '/pose/getCOCO'
    wget_win = musicalgestures._utils.wrap_str(module_path + '/3rdparty/windows/wget/wget.exe')
    target_folder_coco = './'

    if the_system == 'Windows':
        coco_script += batch
    elif in_colab():
        coco_script += shell_colab
    else:
        coco_script += shell

    elif modeltype.lower() == 'coco':
        command = coco_script
        if the_system == 'Windows':
            command += f' {wget_win} {target_folder_coco}'
        else:
            command = 'sudo -S bash ' + command
            command += f' {target_folder_coco}'

    if the_system == 'Windows' or in_colab():
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, 
                                   universal_newlines=True, shell=True)
    else:
        try:
            import getpass
            username = getpass.getuser()
            print(f'[sudo] password for {username}:')
            p = getpass.getpass()
            process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, 
                                       stdin=subprocess.PIPE, universal_newlines=True, shell=True)
            process.stdin.write(p+'\n')
            process.stdin.flush()
        except Exception as error:
            print('ERROR', error)

    try:
        while True:
            out = process.stdout.readline()
            if out == '':
                process.wait()
                break
            elif out.find('%') != -1:
                percentage_place = out.find('%')
                percent = out[percentage_place-2:percentage_place]
            # else:
            #     print(out)

    except KeyboardInterrupt:
        try:
            process.terminate()
        except OSError:
            pass
        process.wait()
        raise KeyboardInterrupt
```
