### ISSUE TITLE
Create MgAudio object

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#273]
We now have MgVideo and MgFigure, but I think it would make sense to have a MgAudio as well to allow for importing only an audio file and do various audio processes on it instead of having to load the audio submodule separately.

**Comment by joachimpoutaraud** [comment]
I have added an `MgAudio` class to import audio files only and do various audio processes on it. I have also updated the `MgVideo` class so that it inherits from the `MgAudio` class. I will update the wiki page for more information and push a new version of the toolbox next week.
