### ISSUE TITLE
Strange inversion

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#275]
There is something strange happening when trying the inverted functions. I don't manage to get inverted_motionvideo to work at all, and inverted_motiongram returns a bw image: 

![Screenshot from 2023-01-12 09-45-19](https://user-images.githubusercontent.com/114316/212019939-f19eacb7-2ec1-4352-a2e0-c9d40282b190.png)

**Comment by joachimpoutaraud** [comment]
I have updated the `_motionvideo.py` file and fixed the problems related to the inversion of the motiongram as well as the inversion of the motionvideo. This was related to the recent reimplementation of the function using `ffmpeg`.
