### ISSUE TITLE
SSM issue

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#276]
When trying to run the SSM function, I get an error: 

> AttributeError: 'QuadMesh' object has no property 'win_length'

See screenshot: 

![Screenshot from 2023-01-12 10-42-06](https://user-images.githubusercontent.com/114316/212032673-96301159-fd40-4452-804c-217d1f30fe9c.png)

**Comment by joachimpoutaraud** [comment]
I have fixed the problem related to the `_ssm.py` file. This was due to a conflict with the different axes used for plotting the SSMs. I have updated the repository and will push a new version of the toolbox asap.
