### ISSUE TITLE
Error with SSM

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#278]
When running [this exampe](https://github.com/fourMs/MGT-python/wiki/4-%E2%80%90-Video%E2%80%90based-Processes#ssm) I get the error: `TypeError: 'MgFigure' object is not callable`: 

![image](https://user-images.githubusercontent.com/114316/213281900-86d89eb2-4ad5-4f46-b515-c0924da04fd8.png)

What is wrong?

**Comment by joachimpoutaraud** [comment]
I guess this has to do with the fact that the `mode='notebook'` is not specified in the `show()` function. Depending on the OS it sometimes do not manage to call the `windowed` mode of the `show` function. I tried on Windows and colab and it works fine. I will try on Linux asap but it the meanwhile you can specify `mode='notebook'` and I think it will solve your problem.

**Comment by alexarje** [comment]
It looks like the problem occurs if you run any processes on the MgVideo object before running ssm. If I load a new video file, it works fine, but if I run any process on the video first (e.g. `motion()`) it gives the MgFigure error.

**Comment by joachimpoutaraud** [comment]
It appears that there was a redundancy in a variable name of the MgFigure object in the `_ssm.py` file. I have found the variable and change its name so that it won't create an error if another process has been executed on the MgVideo object before.
