### ISSUE TITLE
MP4 conversion

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#282]
Why is a .avi file converted to .mp4 by default? Is that for showing in notebook-mode?

![image](https://user-images.githubusercontent.com/114316/213888026-4d629dbc-7b39-4f74-bbb1-e9d203ba5b13.png)

I guess it is fine because, in most cases, people would probably load .mp4 files (myself included).

**Comment by alexarje** [comment]
Ok, here is an odd example of conversion: 

![image](https://user-images.githubusercontent.com/114316/214147668-3d21e6e0-68b4-477f-a2bb-05cb7f6b6be3.png)

Loading a .avi file which is converted back and forth many times... I guess it would be good to avoid converting to mp4 unless one specifies `mode=notebook`?

**Comment by joachimpoutaraud** [comment]
Thanks for reporting that issue! There was actually an `else` statement that was missing in the `__init__` file. The consequence was that every file was systematically converted to mp4. I have fixed the issue and updated the repository.
