### ISSUE TITLE
Direction of SSM

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#283]
I am exploring plotting audio SSMs together with videograms like this: 

![combined-plots](https://user-images.githubusercontent.com/114316/213888435-703fe9cf-a35b-4021-98ff-c05f5652c41a.jpg)

Here I had to manually flip the SSM so that time runs from the top left corner to the bottom right. It would be great to have an option to choose the direction of the SSM.

**Comment by joachimpoutaraud** [comment]
I have updated the ``_ssm.py`` script and added the possibility to invert the y axis from the top left corner to the bottom right with the parameter ``invert_yaxis=False``. Defaults parameter is set to ``True``.
