### ISSUE TITLE
SSM on videograms

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#284]
The SSM currently works with motiongrams but it would be cool to also run it on videograms.

**Comment by joachimpoutaraud** [comment]
I have updated the `_ssm.py` file and added the possibility to render Self-Similarity Matrices on videograms. This can be achieved with the following function

```python
source_video = musicalgestures.MgVideo('/path/to/source/video.avi')
videogram_ssm = source_video.ssm(features='videograms') 
# view results
videogram_ssm.show() # view both SSMs
```
