### ISSUE TITLE
Optional title SSM

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#286]
It would be good to have the possibility to set the title for the SSM functions (similar to waveform(), etc.) and leave it off by default.

**Comment by joachimpoutaraud** [comment]
I have updated the ``_ssm.py`` script and add the possibility to set the title for the SSM functions. By default it is the same as in the waveform script, it renders the os.basename. I have also fix a problem related to the ssm variable name that was redundant and created error when calling the ssm object more than one time.
