### ISSUE TITLE
Metadata rotation

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#287]
FFmpeg supports the rotation of videos in metadata (see [my blog](https://www.arj.no/2021/10/27/video-rotation/) for an example). This would be nice to implement to save some time when one wants to rotate 90 degrees.

**Comment by joachimpoutaraud** [comment]
I have updated the [``rotate_video()``](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_utils.py#L624) function and force the rotation of the video without encoding when rotating by -90,90,-180 or 180 degrees in order to speed up the comuputation.
