### ISSUE TITLE
FFmpeg choking on trimming

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#296]
For some videos, I get a `2 frames left in the queue on closing` error when specifying start and end time. Looking around, this seems to be a [well-known issue](https://stackoverflow.com/questions/60368162/conversion-failed-2-frames-left-in-the-queue-on-closing-ffmpeg) that can be solved by adding `-max_muxing_queue_size 9999`.

**Comment by joachimpoutaraud** [comment]
I have updated the [`extract_subclip`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_utils.py#LL573C2-L573C2) function and added `-max_muxing_queue_size 9999` to the `FFmpeg` command. This should fix the issue.
