### ISSUE TITLE
Float bug in new numpy

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#297]
I upgraded to a new numpy package and get an error with average()

`AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

`

**Comment by joachimpoutaraud** [comment]
Thanks for reporting the issue. I have updated the `_average.py` script which contained `np.float` variables to `np.float32`. I also checked if there was no `np.int` variable that are also deprecated.
