### ISSUE TITLE
Adding more HPSS settings

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#298]
When I try to run the hpss function on my [#StillStanding](https://mastodon.online/tags/StillStanding) videos, I often get more or less black images due to the little sound in the recordings: 

![Screenshot from 2023-07-10 21-13-22](https://github.com/fourMs/MGT-python/assets/114316/19f4fd61-4561-4e64-b59d-505ea606ed0b)

It would be nice to have some options for modifying the sensitivity of the analysis/visualisation, if possible.

**Comment by joachimpoutaraud** [comment]
I have update the `hpss` and `spectrogram` functions of the `MgAudio` object and added an additional `top_db` parameter that can be used to adjust adjust the sensitivity of the visualization.
