### ISSUE TITLE
Index out of range in audio object

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#300]
I get an index error for an audio file. Is there a boundary problem?
![Screenshot from 2023-08-07 09-14-13](https://github.com/fourMs/MGT-python/assets/114316/422cab86-83be-42e2-8df8-ee1161f94d1d)

**Comment by joachimpoutaraud** [comment]
Thanks for reporting the issue! It was just a `try` and `except` issue, where the `except` was associated to a specific error only (`KeyError`). I have removed it so that the function returns now the waveform without any errors in any kind of situation.
