### ISSUE TITLE
Not compatible with python 3.12

### ISSUE THREAD

**Issue by riyasid** [fourMs/MGT-python#303]
<img width="1312" alt="Screen Shot 2023-10-16 at 1 41 01 PM" src="https://github.com/fourMs/MGT-python/assets/148100918/05544936-7873-4d7c-b45c-e491386293cb">

I downloaded the newest version of python and was not able to download the musical gestures toolbox, it worked when I downloaded python 3.11 and deleted 3.12 off my computer. I was then able to download the toolbox, but when running through the demo ran into an issue finding "ffprobe." There was more to the following error message but these seemed like the important parts.
![Screen Shot 2023-10-16 at 5 22 05 PM](https://github.com/fourMs/MGT-python/assets/148100918/79fa9a34-9243-4b67-a1d7-d35da589d9e7)
![Screen Shot 2023-10-16 at 5 22 20 PM](https://github.com/fourMs/MGT-python/assets/148100918/6c669c52-021d-4f26-bc8d-58192947849a)

**Comment by joachimpoutaraud** [comment]
Hi and thank you for reporting this issue! There might be some [issues using Python 3.12 with the library numba](https://github.com/numba/numba/issues/9197) at the moment, so it is preferable to use Python 3.11 instead.

Also, it seems that your error is related to the fact that you do not have `ffprobe` installed on your machine. I recommand you to check the [wiki documentation](https://github.com/fourMs/MGT-python/wiki/0-%E2%80%90-Installation) of the toolbox for properly installing the `FFmpeg` open-source software beforehand.
