### ISSUE TITLE
Blur_faces numpy issue

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#306]
There is a compability issue with the latest version of numpy. Found it when testing the blur_faces() function: 

> AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by joachimpoutaraud** [comment]
Thank you for reporting this issue! I have updated the [`_centerface.py`](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/_centerface.py) script and changed the data type of the numpy array to `bool` instead of `np.bool`.
