### ISSUE TITLE
Progress bar problem blur_faces()

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#307]
On my Ubuntu system, the progress bar in blur_faces() is printed on a new line for each iteration in the notebook. Is it rendered differently from other functions?

**Comment by joachimpoutaraud** [comment]
Thanks for reporting the issue! I have updated several functions with the `-loglevel quiet` parameter for the `FFmpeg` command. This will allow to hide `FFmpeg` outputs so that it won't print a new line for each iteration.
