### ISSUE TITLE
Missing amplitude values in color-waveform

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#309]
I see that the amplitude is plotted as 0. for the amplitude when using the color waveform: 

![Screenshot_20231115_213618](https://github.com/fourMs/MGT-python/assets/114316/8f0bae14-1e9e-4671-890c-99c1be7a331f)

**Comment by joachimpoutaraud** [comment]
Thanks for reporting the issue, I had rounded the amplitude values to one decimal only. I have updated the `_audio.py` script so that it rounds amplitude value below 0.1 to 2 decimals.
