### ISSUE TITLE
Problem with info()

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#316]
The info() function is neat and works well on many videos, but here I came across a video (generated from PupilLabs) that doesn't work: 

![Screenshot_20240106_114951](https://github.com/fourMs/MGT-python/assets/114316/6a9102b3-0ab8-43c7-8736-c5f5eb9f34e2)

I wonder if this is because the file does not have an audio track?

**Comment by joachimpoutaraud** [comment]
Thanks for reporting the issue. Yes, it was indeed due to the fact that the video file hadn't an audio track.
I have updated the `_info.py` script, so that it will take this problem into consideration.
