### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#44]
When I am trying to run the setup file, I get the following problem: 

    $ python setup.py 
    Traceback (most recent call last):
      File "setup.py", line 15, in <module>
        with open(os.path.join(_here, 'motionvideo', 'version.py')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/alexanje/github/MGT-python/motionvideo/version.py'
    
What is wrong?

**Comment by marcuswidmer** [comment]
the setup.py script is unnecessary to run at this point, but can be useful to have in the future.
