### ISSUE TITLE
Error in notebook

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#45]
Testing out the notebook and getting an issues in cell 6: 

      mg = mgmodule.MgObject('dance.avi', starttime = 5, endtime = 15)
      Moviepy - Running:      >>> "+ " ".join(cmd)      Moviepy - Command successful
      ---------------------------------------------------------------------------         NameError                                 Traceback (most recent call last)      <ipython-input-6-b65d648662ba> in <module>      ----> 1 mg = mgmodule.MgObject('dance.avi', starttime = 5, endtime = 15)
      ~/github/MGT-python/mgmodule/__init__.py in __init__(self, filename, method, filtertype, thresh, starttime, endtime, blur, skip, color, contrast, brightness, crop)
          38         self.crop = crop
          39         self.test_input()         ---> 40         self.get_video()
          41 
          42 
      ~/github/MGT-python/mgmodule/__init__.py in get_video(self)
          52     def get_video(self):
          53         """ Creates a video attribute to the Musical Gestures object with the given correct settings. """         ---> 54         self.video, self.length, self.width, self.height, self.fps, self.endtime, self.of = mg_videoreader(self.filename, self.starttime, self.endtime, self.skip, self.contrast, self.brightness, self.crop)
      ~/github/MGT-python/mgmodule/_videoreader.py in mg_videoreader(filename, starttime, endtime, skip, contrast, brightness, crop)
          31         trimvideo = ffmpeg_extract_subclip(filename, starttime, endtime, targetname= of +'_trim' + fex)
          32         of = of + '_trim'         ---> 33         vidcap = cv2.VideoCapture(of+fx)
          34 
          35     # Or just use whole video
      NameError: name 'fx' is not defined

Looks like several issues at once?

**Comment by alexarje** [comment]
This is on Ubuntu, btw.

**Comment by Tony001stark** [comment]
uninstall and re install notebook

>> sudo apt update
>>pip install jupyter

**Comment by marcuswidmer** [comment]
Try again now. I found a typo in _videoreader.py
