### ISSUE TITLE
Keep audio with converted videos

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#48]
It would be nice to have an option to keep audio for converted motion videos. To get this it is probably necessary to either 

1. export the audio from the input video and then add it back in for the converted video. 
2. use ffmpeg to copy audio from source video to output video after conversion.

**Comment by alexarje** [comment]
This could possibly be done with ffmpeg at the end of the chain: 

    ffmpeg -i input1.avi -i input2.avi -c copy -map 1:v:0 -map 0:a:0 -shortest out.avi

We may also possibly want to do a conversion to MP4 last?

**Comment by balintlaczko** [comment]
This is implemented now in my fork, will close this after merging back.

**Comment by alexarje** [comment]
Great!
