### ISSUE TITLE
Invalid style operation

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#56]
On Ubuntu (19.04): I get this error after rendering motionvideo: 

    Rendering motionvideo 100% 
    QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion

What is this?

**Comment by marcuswidmer** [comment]
Is this still an issue?

**Comment by alexarje** [comment]
Probably just a linux thing. Does not seem to affect anything, so I close it.
