### ISSUE TITLE
Adjustment of average image

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#58]
It would be nice to have a normalization function, or be able to adjust the contrast in average_image. This is particularly useful when running it on motion videos, in which there is not so much content.

**Comment by marcuswidmer** [comment]
average image now has an 'enhance' parameter. 'enhance = 1' will scale the brightest pixel to 255 as well as scaling the rest of the image using the same scaling factor. In this way, the image is normalised (has pixel values between 0 and 255).
