### ISSUE TITLE
Inverse colors from mgmotion

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#62]
It would be nice to have an option to choose whether you want white-on-black (normal), or black-on-white (inverted) motion videos and motiongrams coming out mgmotion. Now it returns inverted, which is nice, but sometimes the other is preferable.

**Comment by marcuswidmer** [comment]
Inverted motionvideo, motionhistory and motiongrams are now available.

**Comment by alexarje** [comment]
Great. Just one more thing, I see that when I run 

`mg.mg_motionvideo(inverted_motionvideo = False)`

it returns a normal video (white on black), but inverted motiongrams (black on white). So the inversion setting probably needs to be passed on to the motiongram function too?

**Comment by alexarje** [comment]
Ah, just read in the documentation that it is a separate setting. Good, everything works as expected then.
