### ISSUE TITLE
Export tsv file from mg_motionvideo

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#63]
It would be nice to export a TSV file with quantitative data coming out of mgmotion, similar to what is done in MGT for Matlab.

**Comment by marcuswidmer** [comment]
Done. tsv content description should be made available somewhere maybe? 1st column = qom, 2nd = com(x), 3rd = com(y). Center of motion is normalized. MGT(matlab) does not export normalized values.

**Comment by alexarje** [comment]
Great! I have started a [wiki page](https://github.com/fourMs/MGT-python/wiki) with information about this. 

Only problem is that I think it is using space (not tab) between numbers? Can you fix?

**Comment by marcuswidmer** [comment]
This should be fixed now
