### ISSUE TITLE
Not much contrast in motiongrams

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#71]
Is there any normalization happening in the motion video. I see that the motiongrams are quite dark: 

![dance_trim_cb_mgy](https://user-images.githubusercontent.com/114316/60765468-1e493500-a09b-11e9-8e53-1ce44eea021e.png)

There is more information there, here doing a normalization of the image: 

![dance_trim_cb_mgy-edited](https://user-images.githubusercontent.com/114316/60765469-1e493500-a09b-11e9-8cd3-da881b80d00e.png)

Perhaps we should add normalization as an option?

**Comment by marcuswidmer** [comment]
The motiongrams are already normalized. Line 121 in _motionvideo: 
gramx = gramx/gramx.max() * 255

How did you normalize this? I tried histogram flattening, but I can't get the same result as you.

**Comment by alexarje** [comment]
It works very nice now. Updated the test_dance.py and it outputs something very similar to the Matlab code. Great!
