### ISSUE TITLE
Modules of average and history

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#72]
It would be nice to have modules of the functions average and history as well, so that it is easy to run them on the mg object. Are there any problems with making this?

**Comment by alexarje** [comment]
And: just in the same way that it is possible to create a history file from both regular video and motion video, it would be nice to create an average image also from the motion video.

**Comment by marcuswidmer** [comment]
You can use the 'of' (only-filename) attribute as input to the average_image() function. 

`average_image(mg.of+'_motion.avi') #Average image of motionvideo \\
average_image(mg.of+'.avi') #Average image of the original video`

If we make average_image and history into class methods we loose the ability to use them in this general way. Do you agree?

**Comment by alexarje** [comment]
Yes, that is a good point. It works well like this, it is more a matter of usability, I think. We can try to keep it like this for now, and possibly get back to it later.
