### ISSUE TITLE
Adding skeletons from posenet

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#82]
It would be cool to add a skeleton extraction module, for example, based on [Posenet](https://github.com/rwightman/posenet-python).

**Comment by balintlaczko** [comment]
Implemented the [Pose](https://github.com/fourMs/MGT-python/blob/master/musicalgestures/documentation/_pose.md#pose) module. It outputs the pose data as csv/tsv/txt and renders the skeleton overlay on the input video. It is notoriously very slow, but not slower than what they say [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#cpu-version). Still, in the future it would be good to look for faster alternatives (if those exist). It should support GPU backend, but I cannot try that on my machine.

One problem remains with this is that the models used for this are more than 400 MB together, which is not possible to host/package with the repo. They do have convenient download scripts [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models), so I will make something like that part of the install process.

**Comment by balintlaczko** [comment]
[This](https://towardsdatascience.com/realtime-multiple-person-2d-pose-estimation-using-tensorflow2-x-93e4c156d45f) is TensorFlow-based and claims to be faster, will have a closer look later.

**Comment by balintlaczko** [comment]
A little teaser of the current one :-) The video is 60 FPS, "gififying" brought it down to 15.
![dance_pose_teaser](https://user-images.githubusercontent.com/45127463/98178132-5fa25c80-1efc-11eb-9fb2-079b5354838f.gif)

**Comment by alexarje** [comment]
Nice! And, yes, will be interesting to run on one of the servers with GPU support.

**Comment by balintlaczko** [comment]
Okay, finally got to test this on an nVidia RTX 2070 (mobile). There is a bit of an installation process (- the CUDA SDK, the matching version of cuDNN, and [compiling openCV with CUDA support](https://medium.com/@mhfateen/build-opencv-4-4-0-with-cuda-gpu-support-on-windows-10-without-tears-aa85d470bcd0) - the last step I am not 100% sure was necessary in retrospect), BUT it works, and I didn't have to change anything in the `pose()` method just specify `device='gpu'`. The speed-up is ridiculous 1147% compared to the cpu version (with a 6-core Intel Core i7 10750H).
