### ISSUE TITLE
Fix mg.MotionVideo in ipynb

### ISSUE THREAD

**Issue by shockmonger** [fourMs/MGT-python#86]
name **MotionVideo**  is not an attribute of mg object - it is **mg_motionvideo**
Even this name is clunky imo, maybe we can agree upon a naming strategy, maybe avoid underscore, and add camelcase?

**Comment by balintlaczko** [comment]
Hey there, yeah I already fixed this in my repo: https://github.com/balintlaczko/MGT-python
So in the MgObject class I just import it as motionvideo, like this:
from ._motionvideo import mg_motionvideo as motionvideo
and then if you have an instance of the class:
yo = mgmodule.MgObject('my_cool_vid.avi')
you can just yo.motionvideo() and it starts rendering.

There were similar issues with motionhistory(), show(), and history() (though that case is slightly different), now they can all be called on the class instance directly.

As for the naming strategy, I feel the underscore separation is a bit more pythonic, the camelCase is more of a JS fashion, but as long as we are consistent I am okay with both! :)

**Comment by shockmonger** [comment]
Hi!

I see - this is the wrong repository, maybe I will download your fork and start from there :) I saw the motionhistory() show() and history() issues too - didn't raise them becuase i figured they were the same family. Thanks for the clarifications :)

It's quite right - that underscore is pythonic - but the name redundancies we still need to fix i guess, perhaps that would be good to set out to do anyway!

**Comment by balintlaczko** [comment]
Well this is the repo I want to merge with eventually, we were just advised to fork it, do the work there and then merge back with this one via a pull request. :)

Yes there are a looooot of things needing to be generalized or tidied up, I am sort of doing those things on the fly whenever I have to work with a file. 

And wait, I will invite you to my repo as a collaborator! :)

**Comment by alexarje** [comment]
Great that you are moving on here. Yes, there are lots of issues here, so please fix whatever you find.

**Comment by balintlaczko** [comment]
@alexarje here where we work on the new version: https://github.com/balintlaczko/MGT-python
at this point a lot of things have been fixed/simplified or made more convenient to use. To get an idea open the notebook from that repo, it should show how everything works currently.
