### ISSUE TITLE
Grayscale average image and color motiongram 

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-python#89]
When running 

    mg.MgObject('dance.avi', skip=6).motion(inverted_motiongram=True, inverted_motionvideo=True).average().show()

I get a colored inverted motiongram, but a grayscale inverted average video. Strange...

**Comment by balintlaczko** [comment]
I could reproduce this with the same weird result. I couldn't quite understand how the normalization was implemented earlier, but now I changed it to simply use `cv2.normalize()`, and the problem seems to be solved.
